spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000 # 60초 동안 DB 연결 실패 시 앱 종료하지 않고 재시도

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true


logging.level:
  myex.shopping: INFO
  org.hibernate.SQL: info
  org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: 자동 생성 API
        url: /v3/api-docs
