spring:

  devtools:
    restart:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000 # 60초 동안 DB 연결 실패 시 앱 종료하지 않고 재시도

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true #기존 테이블이 있으면 V1을 실행하지 않고 "이미 적용된 버전"으로 간주하여 계속 진행.
    baseline-version: 1

logging.level:
  myex.shopping: INFO
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: 자동 생성 API
        url: /v3/api-docs
      - name: 수동 작성 문서
        url: /openapi.yaml
